<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('books')->insert([
            // Fiction
            [
                'title' => 'To Kill a Mockingbird',
                'author_id' => 1,
                'publisher_id' => 1,
                'language_id' => 1,
                'pages' => 281,
                'description' => 'Addresses racial injustice in the Deep South.',
                'price' => 14.99,
                'stock_quantity' => 50,
                'sold_count' => 2000,
                'image_url' => 'https://covers.openlibrary.org/b/id/8228691-L.jpg',
                'isbn' => '9780060935467',
                'category_id' => 1,
                'publication_date' => '1960-07-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '1984',
                'author_id' => 2,
                'publisher_id' => 2,
                'language_id' => 1,
                'pages' => 328,
                'description' => 'Dystopian novel about totalitarianism.',
                'price' => 13.45,
                'stock_quantity' => 70,
                'sold_count' => 3000,
                'image_url' => 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
                'isbn' => '9780451524935',
                'category_id' => 1,
                'publication_date' => '1949-06-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Science
            [
                'title' => 'A Brief History of Time',
                'author_id' => 3,
                'publisher_id' => 3,
                'language_id' => 1,
                'pages' => 256,
                'description' => 'Stephen Hawking explains cosmology for the general public.',
                'price' => 18.99,
                'stock_quantity' => 40,
                'sold_count' => 1200,
                'image_url' => 'https://covers.openlibrary.org/b/id/240726-L.jpg',
                'isbn' => '9780553380163',
                'category_id' => 2,
                'publication_date' => '1988-04-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Selfish Gene',
                'author_id' => 4,
                'publisher_id' => 4,
                'language_id' => 1,
                'pages' => 360,
                'description' => 'Richard Dawkins explores evolution and natural selection.',
                'price' => 16.50,
                'stock_quantity' => 60,
                'sold_count' => 1400,
                'image_url' => 'https://covers.openlibrary.org/b/id/8315636-L.jpg',
                'isbn' => '9780198788607',
                'category_id' => 2,
                'publication_date' => '1976-03-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Biography
            [
                'title' => 'The Diary of a Young Girl',
                'author_id' => 5,
                'publisher_id' => 5,
                'language_id' => 1,
                'pages' => 283,
                'description' => 'Anne Frank’s wartime diary.',
                'price' => 12.99,
                'stock_quantity' => 55,
                'sold_count' => 1800,
                'image_url' => 'https://covers.openlibrary.org/b/id/8231991-L.jpg',
                'isbn' => '9780553296983',
                'category_id' => 3,
                'publication_date' => '1947-06-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Long Walk to Freedom',
                'author_id' => 6,
                'publisher_id' => 6,
                'language_id' => 1,
                'pages' => 656,
                'description' => 'Nelson Mandela’s autobiography.',
                'price' => 19.99,
                'stock_quantity' => 30,
                'sold_count' => 900,
                'image_url' => 'https://covers.openlibrary.org/b/id/10221229-L.jpg',
                'isbn' => '9780316548182',
                'category_id' => 3,
                'publication_date' => '1994-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Novel
            [
                'title' => 'Pride and Prejudice',
                'author_id' => 7,
                'publisher_id' => 7,
                'language_id' => 1,
                'pages' => 279,
                'description' => 'Jane Austen’s classic novel of manners.',
                'price' => 11.99,
                'stock_quantity' => 45,
                'sold_count' => 1500,
                'image_url' => 'https://covers.openlibrary.org/b/id/8231856-L.jpg',
                'isbn' => '9780141439518',
                'category_id' => 4,
                'publication_date' => '1813-01-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Catcher in the Rye',
                'author_id' => 8,
                'publisher_id' => 8,
                'language_id' => 1,
                'pages' => 214,
                'description' => 'J.D. Salinger’s coming-of-age novel.',
                'price' => 13.50,
                'stock_quantity' => 35,
                'sold_count' => 1600,
                'image_url' => 'https://covers.openlibrary.org/b/id/8231990-L.jpg',
                'isbn' => '9780316769488',
                'category_id' => 4,
                'publication_date' => '1951-07-16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Moby-Dick',
                'author_id' => 9,
                'publisher_id' => 9,
                'language_id' => 1,
                'pages' => 585,
                'description' => 'Herman Melville’s tale of the whale hunt.',
                'price' => 15.00,
                'stock_quantity' => 20,
                'sold_count' => 700,
                'image_url' => 'https://covers.openlibrary.org/b/id/5551063-L.jpg',
                'isbn' => '9780142437247',
                'category_id' => 4,
                'publication_date' => '1851-11-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Jane Eyre',
                'author_id' => 10,
                'publisher_id' => 10,
                'language_id' => 1,
                'pages' => 500,
                'description' => 'Charlotte Brontë’s novel about morality and love.',
                'price' => 12.50,
                'stock_quantity' => 25,
                'sold_count' => 1200,
                'image_url' => 'https://covers.openlibrary.org/b/id/8226191-L.jpg',
                'isbn' => '9780141441146',
                'category_id' => 4,
                'publication_date' => '1847-10-16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
